name: Selenium Java Tests

on:
  schedule:
    # Schedule your workflow to run at specific times. This example runs daily at 05:00 UTC.
  #  - cron:  '* * * * *'
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the Actions tab.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean test # Adjust if your project uses a different command

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: TestData/TestData.xlsx
